"""Initial commit.

Revision ID: 17724f5cc1c2
Revises: None
Create Date: 2014-11-02 16:02:36.700636

"""

# revision identifiers, used by Alembic.
revision = '17724f5cc1c2'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('team',
    sa.Column('name', sa.String(length=250), nullable=False),
    sa.Column('elo', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('name')
    )
    op.create_table('bet_match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('team_2_name', sa.String(length=250), nullable=True),
    sa.Column('team_1_name', sa.String(length=250), nullable=True),
    sa.Column('team_1_odds', sa.Integer(), nullable=True),
    sa.Column('team_2_odds', sa.Integer(), nullable=True),
    sa.Column('tournament', sa.String(length=250), nullable=True),
    sa.Column('date_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dire_score', sa.Integer(), nullable=True),
    sa.Column('radiant_score', sa.Integer(), nullable=True),
    sa.Column('time', sa.Float(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('winner', sa.String(length=250), nullable=True),
    sa.Column('dire_name', sa.String(length=250), nullable=True),
    sa.Column('radiant_name', sa.String(length=250), nullable=True),
    sa.Column('match_data', sa.Text(), nullable=True),
    sa.Column('dire_elo', sa.Integer(), nullable=True),
    sa.Column('radiant_elo', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dire_name'], ['team.name'], ),
    sa.ForeignKeyConstraint(['radiant_name'], ['team.name'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_match_date'), 'match', ['date'], unique=False)
    op.create_index(op.f('ix_match_dire_name'), 'match', ['dire_name'], unique=False)
    op.create_index(op.f('ix_match_radiant_name'), 'match', ['radiant_name'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_radiant_name'), table_name='match')
    op.drop_index(op.f('ix_match_dire_name'), table_name='match')
    op.drop_index(op.f('ix_match_date'), table_name='match')
    op.drop_table('match')
    op.drop_table('bet_match')
    op.drop_table('team')
    ### end Alembic commands ###
